package com.example.bitonichallenge2.model

const val REQUEST_CODE_PERMISSIONS = 0

const val ACTION_START_OR_RESUME_SERVICE = "ACTION_START_OR_RESUME_SERVICE"
const val ACTION_PAUSE_SERVICE = "ACTION_PAUSE_SERVICE"
const val ACTION_STOP_SERVICE = "ACTION_STOP_SERVICE"
const val ACTION_SHOW_MAPS_ACTIVITY = "ACTION_SHOW_MAPS_ACTIVITY"

const val NOTIFICATION_CHANNEL_ID = "game_channel"
const val NOTIFICATION_CHANNEL_NAME = "game_ongoing"
// At least to 1 to work
const val NOTIFICATION_ID = 1